name: built_union_test
version: 0.1.3
description: >
  Dart sum-types, compatible with built_value.dart
  This library contains integration tests for built_union.dart
homepage: https://github.com/freedomlayer/built_union.dart

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    meta: ^1.3.0
    built_value: ^8.0.5
    built_union: ^0.2.0
    built_collection: ^5.0.0
    test: ^1.17.2

dev_dependencies:
    built_value_generator: ^8.0.5
    built_union_generator: ^0.2.0
    build_runner: ^1.0.0

