#!/usr/bin/env bash

set -e

directories="built_union built_union_generator built_union_test"

parent_directory=$PWD

# Use local dependencies, to make sure we are testing against our code
# and not against remote dependencies
cd $parent_directory
$parent_directory/tool/local_deps enable

for directory in $directories; do
  echo
  echo "*** Formatting $directory..."
  echo
  cd "$parent_directory/$directory"

  dartfmt -w $(find bin lib test -name \*.dart 2>/dev/null)
done

for directory in $directories; do
  echo
  echo "*** Building $directory..."
  echo
  cd "$parent_directory/$directory"

  pub get
  pub upgrade

  # Clear any pre-existing build output:
  rm -rf .dart_tool/build/

  grep -q build_runner pubspec.yaml && \
      pub run build_runner build \
          --delete-conflicting-outputs \
          --fail-on-severe
done

for directory in $directories; do
  echo
  echo "*** Analyzing $directory..."
  echo
  cd "$parent_directory/$directory"

  dartanalyzer \
      --fatal-warnings \
      --fatal-infos \
      --packages="$PWD/.packages" \
      $(find bin lib test -name \*.dart 2>/dev/null)
done

for directory in $directories; do
  echo
  echo "*** Testing $directory..."
  echo
  cd "$parent_directory/$directory"

  pub run test
done

# Restore remote dependencies
cd $parent_directory
$parent_directory/tool/local_deps disable
