name: built_union
version: 0.2.0
description: >
  Dart sum-types, compatible with built_value.dart
  This library is the runtime dependency.
homepage: https://github.com/freedomlayer/built_union.dart

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    meta: ^1.3.0
    built_value: ^8.0.5
    built_collection: ^5.0.0

dev_dependencies:
    test: ^1.17.2
